AllCops:
    NewCops: enable
    Excludes:
      - 'db/schema.rb'
      - 'bin/*'
      - 'log/*'
      - 'tmp/*'
      - 'node_modules/**/*'
      - 'vendor/**/*'
      - 'spec/fixtures/**/*'
      - 'spec/support/**/*'

Metrics/BlockLength:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
